"""agregar soporte de regiones a punto_medicion

Revision ID: a56ad45ccabb
Revises: 
Create Date: 2026-09-01 21:29:31.763708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a56ad45ccabb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('informe')
    op.drop_table('imagen_termografica')
    op.drop_table('punto_medicion')
    op.create_index(op.f('ix_rol_id_rol'), 'rol', ['id_rol'], unique=False)
    op.create_index(op.f('ix_usuario_correo_usuario'), 'usuario', ['correo_usuario'], unique=True)
    op.create_index(op.f('ix_usuario_id_usuario'), 'usuario', ['id_usuario'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuario_id_usuario'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_correo_usuario'), table_name='usuario')
    op.drop_index(op.f('ix_rol_id_rol'), table_name='rol')
    op.create_table('punto_medicion',
    sa.Column('id_punto', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('etiqueta', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('valor_temp', mysql.DECIMAL(precision=6, scale=2), nullable=True),
    sa.Column('id_imagen', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_imagen'], ['imagen_termografica.id_imagen'], name=op.f('fk_punto_imagen')),
    sa.PrimaryKeyConstraint('id_punto'),
    mysql_collate='utf8mb4_uca1400_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('imagen_termografica',
    sa.Column('id_imagen', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nombre_archivo', mysql.VARCHAR(length=300), nullable=False),
    sa.Column('fecha_modificacion', mysql.DATETIME(), nullable=True),
    sa.Column('ancho', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('alto', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('formato', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('modelo_camara', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('numero_serie', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('distancia_focal', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('numero_f', mysql.DECIMAL(precision=4, scale=2), nullable=True),
    sa.Column('latitud', mysql.DECIMAL(precision=10, scale=6), nullable=True),
    sa.Column('longitud', mysql.DECIMAL(precision=10, scale=6), nullable=True),
    sa.Column('distancia_m', mysql.DECIMAL(precision=6, scale=2), nullable=True),
    sa.Column('humedad', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('emisividad', mysql.DECIMAL(precision=4, scale=2), nullable=True),
    sa.Column('temp_reflejada', mysql.DECIMAL(precision=6, scale=2), nullable=True),
    sa.Column('temp_max', mysql.DECIMAL(precision=6, scale=2), nullable=True),
    sa.Column('temp_min', mysql.DECIMAL(precision=6, scale=2), nullable=True),
    sa.Column('id_usuario', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('id_informe', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_informe'], ['informe.id_informe'], name=op.f('fk_imagen_informe')),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], name=op.f('fk_imagen_usuario')),
    sa.PrimaryKeyConstraint('id_imagen'),
    mysql_collate='utf8mb4_uca1400_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('informe',
    sa.Column('id_informe', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('fecha_generacion', sa.DATE(), server_default=sa.text('curdate()'), nullable=True),
    sa.Column('nivel_riesgo', mysql.VARCHAR(length=400), nullable=True),
    sa.Column('observaciones', mysql.TEXT(), nullable=True),
    sa.Column('estado', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('nombre_archivo', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('ruta_pdf', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('id_usuario', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], name=op.f('fk_informe_usuario')),
    sa.PrimaryKeyConstraint('id_informe'),
    mysql_collate='utf8mb4_uca1400_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
